project:
  type: book

number-sections: false

book:
  title: "BIOS_IN5410/9410: Reproducible Bioinformatics Analysis"
  author: "Lex Nederbragt"
  date: today
  chapters:
    - index.qmd
    - day1.qmd
    - day2.qmd
    - day3.qmd

#bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
